//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDemo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class treeModelEntities : DbContext
    {
        public treeModelEntities()
            : base("name=treeModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TreeItem> TreeItems { get; set; }
        public virtual DbSet<TreeItemType> TreeItemTypes { get; set; }
        public virtual DbSet<TreeState> TreeStates { get; set; }
    }
}
